### ISSUE TITLE
Couldn't start client Ember Language Server

### ISSUE THREAD

**Issue by lolmaus** [emberwatch/vscode-ember#6]
```
mainThreadExtensionService.ts:44
Error: listen EMFILE /tmp/vscode-d3ec8d3ae6235c174f6d61ffdc355f61cec6f724.sock
	at Object.exports._errnoException (util.js:1050:11)
	at exports._exceptionWithHostPort (util.js:1073:20)
	at Server.setupListenHandle [as _listen2] (net.js:1247:19)
	at listenInCluster (net.js:1304:12)
	at Server.listen (net.js:1413:5)
	at Object.fork (/home/lolmaus/.vscode/extensions/emberjs.vscode-ember-0.1.1/node_modules/vscode-languageclient/lib/utils/electron.js:72:12)
	at client_1.BaseLanguageClient.createMessageTransports.Promise (/home/lolmaus/.vscode/extensions/emberjs.vscode-ember-0.1.1/node_modules/vscode-languageclient/lib/main.js:269:34)
	at Promise (<anonymous>)
	at LanguageClient.createMessageTransports (/home/lolmaus/.vscode/extensions/emberjs.vscode-ember-0.1.1/node_modules/vscode-languageclient/lib/main.js:249:24)
	at LanguageClient.createConnection (/home/lolmaus/.vscode/extensions/emberjs.vscode-ember-0.1.1/node_modules/vscode-languageclient/lib/client.js:1854:21)
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
```

```
messageService.ts:126
Couldn't start client Ember Language Server
e.doShow @ messageService.ts:126
```

Please help.

**Comment by lolmaus** [comment]
Ok, this seems to resolve the issue: https://easyengine.io/tutorials/linux/increase-open-files-limit/
